//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusClient.ServiceMusReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusData", Namespace="http://schemas.datacontract.org/2004/07/MusWinService")]
    [System.SerializableAttribute()]
    public partial class MusData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusTeamData[] MusTeamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PointsToWinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusTeamData[] MusTeams {
            get {
                return this.MusTeamsField;
            }
            set {
                if ((object.ReferenceEquals(this.MusTeamsField, value) != true)) {
                    this.MusTeamsField = value;
                    this.RaisePropertyChanged("MusTeams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PointsToWin {
            get {
                return this.PointsToWinField;
            }
            set {
                if ((this.PointsToWinField.Equals(value) != true)) {
                    this.PointsToWinField = value;
                    this.RaisePropertyChanged("PointsToWin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusTeamData", Namespace="http://schemas.datacontract.org/2004/07/MusWinService")]
    [System.SerializableAttribute()]
    public partial class MusTeamData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserName2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamName {
            get {
                return this.TeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamNameField, value) != true)) {
                    this.TeamNameField = value;
                    this.RaisePropertyChanged("TeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName1 {
            get {
                return this.UserName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserName1Field, value) != true)) {
                    this.UserName1Field = value;
                    this.RaisePropertyChanged("UserName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName2 {
            get {
                return this.UserName2Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserName2Field, value) != true)) {
                    this.UserName2Field = value;
                    this.RaisePropertyChanged("UserName2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMusReference.IMusService")]
    public interface IMusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/Login", ReplyAction="http://tempuri.org/IMusService/LoginResponse")]
        string Login(string userName, string gameName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/Login", ReplyAction="http://tempuri.org/IMusService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string userName, string gameName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/GetConnectedUsers", ReplyAction="http://tempuri.org/IMusService/GetConnectedUsersResponse")]
        string[] GetConnectedUsers(string gameName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/GetConnectedUsers", ReplyAction="http://tempuri.org/IMusService/GetConnectedUsersResponse")]
        System.Threading.Tasks.Task<string[]> GetConnectedUsersAsync(string gameName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/CreateTeam", ReplyAction="http://tempuri.org/IMusService/CreateTeamResponse")]
        string CreateTeam(string gameName, string teamName, string[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/CreateTeam", ReplyAction="http://tempuri.org/IMusService/CreateTeamResponse")]
        System.Threading.Tasks.Task<string> CreateTeamAsync(string gameName, string teamName, string[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/StartGame", ReplyAction="http://tempuri.org/IMusService/StartGameResponse")]
        string StartGame(string gameName, int pointsToWin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/StartGame", ReplyAction="http://tempuri.org/IMusService/StartGameResponse")]
        System.Threading.Tasks.Task<string> StartGameAsync(string gameName, int pointsToWin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/GetMusData", ReplyAction="http://tempuri.org/IMusService/GetMusDataResponse")]
        MusData GetMusData(string gameName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/GetMusData", ReplyAction="http://tempuri.org/IMusService/GetMusDataResponse")]
        System.Threading.Tasks.Task<MusData> GetMusDataAsync(string gameName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/GetCards", ReplyAction="http://tempuri.org/IMusService/GetCardsResponse")]
        Common.Enums.MusCard[] GetCards(string gameName, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/GetCards", ReplyAction="http://tempuri.org/IMusService/GetCardsResponse")]
        System.Threading.Tasks.Task<Common.Enums.MusCard[]> GetCardsAsync(string gameName, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/ChangeCards", ReplyAction="http://tempuri.org/IMusService/ChangeCardsResponse")]
        Common.Enums.MusCard[] ChangeCards(string gameName, string userName, Common.Enums.MusCard[] discarded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/ChangeCards", ReplyAction="http://tempuri.org/IMusService/ChangeCardsResponse")]
        System.Threading.Tasks.Task<Common.Enums.MusCard[]> ChangeCardsAsync(string gameName, string userName, Common.Enums.MusCard[] discarded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/ChangePoints", ReplyAction="http://tempuri.org/IMusService/ChangePointsResponse")]
        void ChangePoints(string gameName, string teamName, int points);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/ChangePoints", ReplyAction="http://tempuri.org/IMusService/ChangePointsResponse")]
        System.Threading.Tasks.Task ChangePointsAsync(string gameName, string teamName, int points);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/ResetRound", ReplyAction="http://tempuri.org/IMusService/ResetRoundResponse")]
        void ResetRound(string gameName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusService/ResetRound", ReplyAction="http://tempuri.org/IMusService/ResetRoundResponse")]
        System.Threading.Tasks.Task ResetRoundAsync(string gameName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusServiceChannel : IMusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusServiceClient : System.ServiceModel.ClientBase<IMusService>, IMusService {
        
        public MusServiceClient() {
        }
        
        public MusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string userName, string gameName, string password) {
            return base.Channel.Login(userName, gameName, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string userName, string gameName, string password) {
            return base.Channel.LoginAsync(userName, gameName, password);
        }
        
        public string[] GetConnectedUsers(string gameName) {
            return base.Channel.GetConnectedUsers(gameName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetConnectedUsersAsync(string gameName) {
            return base.Channel.GetConnectedUsersAsync(gameName);
        }
        
        public string CreateTeam(string gameName, string teamName, string[] users) {
            return base.Channel.CreateTeam(gameName, teamName, users);
        }
        
        public System.Threading.Tasks.Task<string> CreateTeamAsync(string gameName, string teamName, string[] users) {
            return base.Channel.CreateTeamAsync(gameName, teamName, users);
        }
        
        public string StartGame(string gameName, int pointsToWin) {
            return base.Channel.StartGame(gameName, pointsToWin);
        }
        
        public System.Threading.Tasks.Task<string> StartGameAsync(string gameName, int pointsToWin) {
            return base.Channel.StartGameAsync(gameName, pointsToWin);
        }
        
        public MusData GetMusData(string gameName) {
            return base.Channel.GetMusData(gameName);
        }
        
        public System.Threading.Tasks.Task<MusData> GetMusDataAsync(string gameName) {
            return base.Channel.GetMusDataAsync(gameName);
        }
        
        public Common.Enums.MusCard[] GetCards(string gameName, string userName) {
            return base.Channel.GetCards(gameName, userName);
        }
        
        public System.Threading.Tasks.Task<Common.Enums.MusCard[]> GetCardsAsync(string gameName, string userName) {
            return base.Channel.GetCardsAsync(gameName, userName);
        }
        
        public Common.Enums.MusCard[] ChangeCards(string gameName, string userName, Common.Enums.MusCard[] discarded) {
            return base.Channel.ChangeCards(gameName, userName, discarded);
        }
        
        public System.Threading.Tasks.Task<Common.Enums.MusCard[]> ChangeCardsAsync(string gameName, string userName, Common.Enums.MusCard[] discarded) {
            return base.Channel.ChangeCardsAsync(gameName, userName, discarded);
        }
        
        public void ChangePoints(string gameName, string teamName, int points) {
            base.Channel.ChangePoints(gameName, teamName, points);
        }
        
        public System.Threading.Tasks.Task ChangePointsAsync(string gameName, string teamName, int points) {
            return base.Channel.ChangePointsAsync(gameName, teamName, points);
        }
        
        public void ResetRound(string gameName) {
            base.Channel.ResetRound(gameName);
        }
        
        public System.Threading.Tasks.Task ResetRoundAsync(string gameName) {
            return base.Channel.ResetRoundAsync(gameName);
        }
    }
}
